### ISSUE TITLE
transition cause focus problem

### ISSUE THREAD

**Issue by johnchenkzy** [h16nning/typora-gitbook-theme#24] opened 2021-06-09 05:59 UTC
In Windows 10 system , Typora version : 0.10.11. if not focus(select) on sidebar item,sidebar drop item will flash across . i debug this issue, It's cause by transition code.
![3](https://user-images.githubusercontent.com/16695997/121301192-68439100-c92a-11eb-9d7c-3135105655dd.gif)

```css
.file-tree-node:not(.file-node-root):not(.file-node-expanded)
    .file-node-background {
    transition-duration: 0.2s;
    transition-property: background-color;
}
```
remove this code, problem resolve. maybe another solution?

**Comment by 16soundsofsilence** [comment] 2021-06-12 14:30
Hi, the issue has been resolved in the [latest release](https://github.com/16soundsofsilence/typora-gitbook-theme/releases/latest).

**Comment by blockomat2100** [comment] 2021-07-13 13:52
This issue happens on Linux too (saw this on Fedora and Debian). If I remove the code shown above, the problem is gone.

**Comment by 16soundsofsilence** [comment] 2021-07-13 21:17
@blockomat2100 Thanks for mentioning this. I updated the labels.

**Comment by h16nning** [comment] 2021-07-23 12:17
Hi @blockomat2100, the issue shouldn't occur anymore in version 1.10.3. Unfortunately I can't test this with my current setup, so I would really appreciate it, if you gave me a short feedback whether it's actually fixed.

**Closed** 2021-07-25 21:43 UTC
Labels: bug, linux, windows

**Comment by blockomat2100** [comment] 2021-07-31 02:56
@h16nning, thanks. Seems to be fixed :)
